INSERT INTO category (description)  VALUES ('American');
INSERT INTO category (description)  VALUES ('Italian');
INSERT INTO category (description)  VALUES ('Mexican');
INSERT INTO category (description)  VALUES ('Fast Food');
INSERT INTO unit_of_measure (description)  VALUES ('Teaspoon');
INSERT INTO unit_of_measure (description)  VALUES ('Tablespoon');
INSERT INTO unit_of_measure (description)  VALUES ('Cup');
INSERT INTO UNIT_OF_MEASURE (description)  VALUES ('Pinch');
INSERT INTO UNIT_OF_MEASURE (description)  VALUES ('Ounce');
INSERT INTO UNIT_OF_MEASURE (description)  VALUES ('Each');
INSERT INTO UNIT_OF_MEASURE (description)  VALUES ('Dash');
INSERT INTO UNIT_OF_MEASURE (description)  VALUES ('Pint');
